package vocab

import (
	"math/rand"
	"time"
)

var nCosmos = []string{
	"cosmos",
	"quantum soup",
	"infinite",
	"universe",
	"galaxy",
	"multiverse",
	"grid",
	"quantum matrix",
	"totality",
	"quantum cycle",
	"nexus",
	"planet",
	"solar system",
	"world",
	"stratosphere",
	"dreamscape",
	"biosphere",
}

var nPerson = []string{
	"being",
	"child",
	"traveller",
	"entity",
	"lifeform",
	"wanderer",
	"visitor",
	"prophet",
	"seeker",
}

var nPersonPlural = []string{
	"beings",
	"travellers",
	"entities",
	"lifeforms",
	"dreamweavers",
	"adventurers",
	"pilgrims",
	"warriors",
	"messengers",
	"dreamers",
	"storytellers",
	"seekers",
}

var nMass = []string{
	"consciousness",
	"nature",
	"beauty",
	"knowledge",
	"truth",
	"life",
	"healing",
	"potential",
	"freedom",
	"purpose",
	"coherence",
	"choice",
	"passion",
	"understanding",
	"balance",
	"growth",
	"inspiration",
	"conscious living",
	"energy",
	"health",
	"spacetime",
	"learning",
	"being",
	"wisdom",
	"stardust",
	"sharing",
	"science",
	"curiosity",
	"hope",
	"wonder",
	"faith",
	"fulfillment",
	"peace",
	"rebirth",
	"self-actualization",
	"presence",
	"power",
	"will",
	"flow",
	"potential",
	"potentiality",
	"chi",
	"intuition",
	"synchronicity",
	"wellbeing",
	"joy",
	"love",
	"karma",
	"life-force",
	"awareness",
	"guidance",
	"transformation",
	"grace",
	"divinity",
	"non-locality",
	"inseparability",
	"interconnectedness",
	"transcendence",
	"empathy",
	"insight",
	"rejuvenation",
	"ecstasy",
	"aspiration",
	"complexity",
	"serenity",
}

var nMassBad = []string{
	"turbulence",
	"pain",
	"suffering",
	"stagnation",
	"desire",
	"bondage",
	"greed",
	"selfishness",
	"ego",
	"dogma",
	"illusion",
	"delusion",
	"yearning",
	"discontinuity",
	"materialism",
}

var nOurPlural = []string{
	"souls",
	"lives",
	"dreams",
	"hopes",
	"bodies",
	"hearts",
	"brains",
	"third eyes",
	"essences",
	"chakras",
}

var nPath = []string{
	"circuit",
	"mission",
	"journey",
	"path",
	"quest",
	"vision quest",
	"story",
	"myth",
}

var nOf = []string{
	"quantum leap",
	"evolution",
	"spark",
	"lightning bolt",
	"reintegration",
	"vector",
	"rebirth",
	"revolution",
	"wellspring",
	"fount",
	"source",
	"fusion",
	"canopy",
	"flow",
	"network",
	"current",
	"transmission",
	"oasis",
	"quantum shift",
	"paradigm shift",
	"metamorphosis",
	"harmonizing",
	"reimagining",
	"rekindling",
	"unifying",
	"osmosis",
	"vision",
	"uprising",
	"explosion",
}

var ing = []string{
	"flowering",
	"unfolding",
	"blossoming",
	"awakening",
	"deepening",
	"refining",
	"maturing",
	"evolving",
	"summoning",
	"unveiling",
	"redefining",
	"condensing",
	"ennobling",
}

var adj = []string{
	"enlightened",
	"zero-point",
	"quantum",
	"high-frequency",
	"Vedic",
	"non-dual",
	"conscious",
	"sentient",
	"sacred",
	"infinite",
	"primordial",
	"ancient",
	"powerful",
	"spiritual",
	"higher",
	"advanced",
	"internal",
	"sublime",
	"technological",
	"dynamic",
	"life-affirming",
	"sensual",
	"unrestricted",
	"ever-present",
	"endless",
	"ethereal",
	"astral",
	"cosmic",
	"spatial",
	"transformative",
	"unified",
	"non-local",
	"mystical",
	"divine",
	"self-aware",
	"magical",
	"amazing",
	"interstellar",
	"unlimited",
	"authentic",
	"angelic",
	"karmic",
	"psychic",
	"pranic",
	"consciousness-expanding",
	"perennial",
	"heroic",
	"archetypal",
	"mythic",
	"intergalatic",
	"holistic",
	"joyous",
	"sublime",
}

var adjBig = []string{
	"epic",
	"unimaginable",
	"colossal",
	"unfathomable",
	"magnificent",
	"enormous",
	"jaw-dropping",
	"ecstatic",
	"powerful",
	"untold",
	"astonishing",
	"incredible",
	"breathtaking",
	"staggering",
}

var adjWith = []string{
	"aglow with",
	"buzzing with",
	"beaming with",
	"full of",
	"overflowing with",
	"radiating",
	"bursting with",
	"electrified with",
}

var adjPrefix = []string{
	"ultra-",
	"supra-",
	"hyper-",
	"pseudo-",
}

var vtMass = []string{
	"inspire",
	"integrate",
	"ignite",
	"discover",
	"rediscover",
	"foster",
	"release",
	"manifest",
	"harmonize",
	"engender",
	"bring forth",
	"bring about",
	"create",
	"spark",
	"reveal",
	"generate",
	"leverage",
}

var vtPerson = []string{
	"enlighten",
	"inspire",
	"empower",
	"unify",
	"strengthen",
	"recreate",
	"fulfill",
	"change",
	"develop",
	"heal",
	"awaken",
	"synergize",
	"ground",
	"bless",
	"beckon",
}

var viPerson = []string{
	"exist",
	"believe",
	"grow",
	"live",
	"dream",
	"reflect",
	"heal",
	"vibrate",
	"self-actualize",
}

var vtDestroy = []string{
	"destroy",
	"eliminate",
	"shatter",
	"disrupt",
	"sabotage",
	"exterminate",
	"obliterate",
	"eradicate",
	"extinguish",
	"erase",
	"confront",
}

var nTheXOf = []string{
	"richness",
	"truth",
	"growth",
	"nature",
	"healing",
	"knowledge",
}

var ppPerson = []string{
	"awakened",
	"re-energized",
	"recreated",
	"reborn",
	"guided",
	"aligned",
}

var ppThingPrep = []string{
	"enveloped in",
	"transformed into",
	"nurtured by",
	"opened by",
	"immersed in",
	"engulfed in",
	"baptized in",
}

var fixedAdvP = []string{
	"through non-local interactions",
	"inherent in nature",
	"at the quantum level",
	"at the speed of light",
	"of unfathomable proportions",
	"on a cosmic scale",
	"devoid of self",
	"of the creative act",
}

var fixedAdvPPlace = []string{
	"in this dimension",
	"outside time",
	"within the Godhead",
	"at home in the cosmos",
}

var fixedNP = []string{
	"expanding wave functions",
	"superpositions of possibilities",
	"electromagnetic forces",
	"electromagnetic resonance",
	"molecular structures",
	"atomic ionization",
	"electrical impulses",
	"a resonance cascade",
	"bio-electricity",
	"ultrasonic energy",
	"sonar energy",
	"vibrations",
	"frequencies",
	"four-dimensional superstructures",
	"ultra-sentient particles",
	"sub-atomic particles",
	"chaos-driven reactions",
	"supercharged electrons",
	"supercharged waveforms",
	"pulses",
	"transmissions",
	"morphogenetic fields",
	"bio-feedback",
	"meridians",
	"morphic resonance",
}

var nSubject = []string{
	"alternative medicine",
	"astrology",
	"tarot",
	"crystal healing",
	"the akashic record",
	"feng shui",
	"acupuncture",
	"homeopathy",
	"aromatherapy",
	"ayurvedic medicine",
	"faith healing",
	"prayer",
	"astral projection",
	"Kabala",
	"reiki",
	"naturopathy",
	"numerology",
	"affirmations",
	"the Law of Attraction",
}

var vOpenUp = []string{
	"open up",
	"give us access to",
	"enable us to access",
	"remove the barriers to",
	"clear a path toward",
	"let us access",
	"tap into",
	"align us with",
}

var vTraverse = []string{
	"traverse",
	"walk",
	"follow",
	"engage with",
	"go along",
	"roam",
	"navigate",
	"wander",
	"embark on",
}

var replacements = map[string][]string{
	"nCosmos":        nCosmos,
	"nPerson":        nPerson,
	"nPersonPlural":  nPersonPlural,
	"nMass":          nMass,
	"nMassBad":       nMassBad,
	"nOurPlural":     nOurPlural,
	"nPath":          nPath,
	"nOf":            nOf,
	"ing":            ing,
	"adj":            adj,
	"adjBig":         adjBig,
	"adjWith":        adjWith,
	"adjPrefix":      adjPrefix,
	"vtMass":         vtMass,
	"vtPerson":       vtPerson,
	"viPerson":       viPerson,
	"vtDestroy":      vtDestroy,
	"nTheXOf":        nTheXOf,
	"ppPerson":       ppPerson,
	"ppThingPrep":    ppThingPrep,
	"fixedAdvP":      fixedAdvP,
	"fixedAdvPPlace": fixedAdvPPlace,
	"fixedNP":        fixedNP,
	"nSubject":       nSubject,
	"vOpenUp":        vOpenUp,
	"vTraverse":      vTraverse,
}

// Replace if word matches any of the replacement keys choose a random replacement
func Replace(word string) string {
	if _, ok := replacements[word]; ok {
		idx := randInt(len(replacements[word]) - 1)
		return replacements[word][idx]
	}
	return word
}

func randInt(max int) int {
	if max == 0 {
		return max
	}
	rand.Seed(time.Now().UnixNano())
	return rand.Intn(max)
}
